apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: microtodo-pvc
  namespace: dev

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: managed-csi  

  resources:
    requests:
      storage: 500Mi