---
- name: Configure application servers
  hosts: webservers
  become: true

  tasks:

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - curl
          - unzip
        state: present
        update_cache: true

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Start Docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true